import mongoose from 'mongoose';

const waterSampleSchema = new mongoose.Schema({
    Client: String,
    Address: String,
    City: String,
    State: String,
    ZIP: String,
    Operator: String,
    Date: Date,
    Sample: String,
    Conductivity: Number,
    'Conductivity (Controller)': Number,
    'Neutralized Conductivity': Number,
    TDS: Number,
    Cycles: Number,
    'Calcium Hardness Cycles': Number,
    'Alkalinity Cycles': Number,
    pH: Number,
    'pH (Controller)': Number,
    ORP: Number,
    LSI: Number,
    'LSI (95°F)': Number,
    'LSI (90°F)': Number,
    'LSI (80°F)': Number,
    Temperature: Number,
    'Calcium Hardness': Number,
    'Total Hardness': Number,
    'Total Alkalinity': Number,
    'P Alkalinity': Number,
    'OH Alkalinity': Number,
    Copper: Number,
    Organophosphonate: Number,
    Ryznar: Number,
    Chlorides: Number,
    'Free Chlorine': Number,
    'Total Chlorine': Number,
    'Oxidant (Controller)': Number,
    'Minutes After Oxidant Feed': Number,
    'Total Bromine': Number,
    'Chlorine Dioxide': Number,
    Molybdate: Number,
    Iron: Number,
    Azole: Number,
    Polymer: Number,
    PTSA: Number,
    'PTSA (Controller)': Number,
    Silica: Number,
    Bacteria: Number,
    Nitrite: Number,
    Sulfite: Number,
    Turbidity: Number,
    Cetamine: Number,
    'Water Meter': Number,
});

const water_sample_data = mongoose.model('client', waterSampleSchema);

export default water_sample_data;